import { FAMILY_IDS } from "./toonFamilies"

export const AUCTION_CONTRACT_ADDRESS =
  "0xaaa688ac2755cb6a27d123a0300bcf793c9ed019"

export const TOON_CONTRACT_ADDRESSES = {}

/**
 * CONTRACTS ON MAIN NET
 */

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Cows] =
  "0x8a272d4057a469426b7334843b97ff2a18bead04"

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Bulls] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Donkeys] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Elephants] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Gorillas] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Hippos] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Llamas] = ""
