import { FAMILY_IDS } from "./toonFamilies"

export const AUCTION_CONTRACT_ADDRESS =
  "0xaaa688ac2755cb6a27d123a0300bcf793c9ed019"

export const TOON_CONTRACT_ADDRESSES = {}

/**
 * CONTRACTS ON MAIN NET
 */

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Cows] =
  "0xd4202b234c15255bf0511d3380e83bda9172a72b"

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Bulls] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Donkeys] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Elephants] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Gorillas] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Hippos] = ""

TOON_CONTRACT_ADDRESSES[FAMILY_IDS.Llamas] = ""
